/*
 *  CVS Version: $Id: ios-config.c,v 1.8 2013/08/05 14:31:08 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <unistd.h>
#include <stdlib.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_cli.h>

/* local */
#include "ios.h"

/*
 * Show running config
 */
int
ios_show_running(clicon_handle h, cvec *vars, cg_var *arg)
{
    cli_ios_show_running(h);
    return 0;
}

/*
 * Show startup configuration
 */
int
ios_show_startup(clicon_handle h, cvec *vars, cg_var *arg)
{
    cli_ios_show_config(h, clicon_startup_config(h));
    return 0;
}

/*
 * Show startup configuration
 */
int
ios_show_archive_diff(clicon_handle h, cvec *vars, cg_var *arg)
{
    cg_var *cv1 = cvec_i(vars, 1);

    ios_cli_show_archive_diff(h, cv_string_get(cv1));
    return 0;
}

