/*
 *  CVS Version: $Id: linux-tunnel.c,v 1.6 2013/08/09 13:27:46 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <errno.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_cli.h>

/* rost lib */
#include <quaggapi.h>
#include <linux-tunnel.h>

/* local */
#include "ios.h"



int 
tunnel_add_interface(clicon_handle h, cvec *vars, cg_var *arg)
{
    cg_var *cv1 = NULL;
    cg_var *cv2 = NULL;
    cg_var *ifname;
    char *str;
    int autocommit;
    int retval = -1;

    /* Save autocommit value */
    autocommit = clicon_autocommit(h);
    /* Disable autocommit as we need to get both keys into the candidate
       before committing. 
       XXX this should be fixed with a decent db manuplation API outside
       cli_set() & co
    */
    clicon_autocommit_set(h, 0);

    /* Get specified interface name */
    if ((ifname = cvec_find_var(vars, "name")) == NULL) {
	clicon_err(OE_CFG, ENOENT, "Could not find 'name' in variable vector");
	goto catch;
    }

    /* Build cgv for cli_ios_mode() */
    if ((cv1 = cv_new(CGV_INT)) == NULL){
	fprintf(stderr, "%s: cv_new: %s\n", __FUNCTION__, strerror(errno));
	goto catch;
    }
    cv_int_set(cv1, IOS_MODE_INTERFACE);
    if (cli_ios_mode(h, vars, cv1)) {
	
	/* cli_ios_mode() was successful,not add tunnel mode key */
	str = chunk_sprintf(__FUNCTION__,
			    "interface[].unit[].tunnel.mode $!name=(string)\"%s\" $!unit=(int)0 $mode=(string)\"%s\"",
			    cv_string_get(ifname),
			    cv_string_get(arg));
	if (str == NULL) {
	    clicon_err(OE_UNIX, errno, "chunk");
	    goto catch;
	}
	if ((cv2 = cv_new(CGV_STRING)) == NULL){
	    fprintf(stderr, "%s: cv_new: %s\n", __FUNCTION__, strerror(errno));
	    goto catch;
	}
	if(cv_parse(str, cv2) < 0) {
	    clicon_err(OE_CFG, EINVAL, "Failed to parse new cgv");
	    goto catch;
	}
	/* restore autocommit setting */
	clicon_autocommit_set(h, autocommit);
	if (cli_set (h, vars, cv2) < 0)
	    goto catch;
    }
    
    retval = 0;

catch:
    if (cv1)
	cv_free(cv1);
    if (cv2)
	cv_free(cv2);

    /* restore autocommit setting */
    clicon_autocommit_set(h, autocommit);
    unchunk_group(__FUNCTION__);
    return retval;
}

/*
 * tunnel_set
 * Wrapper around cli_set to make sure we've got a tunnel interface
 */
int
tunnel_set(clicon_handle h, cvec *vars, cg_var *arg)
{
    int matchlen;

    matchlen = clicon_strmatch(cli_mode.u.iface, LINUX_TUNNEL_IFRX_FULL, NULL);
    if (matchlen <= 0) {
	cli_output(stderr, "Only supported on tunnel interfaces\n");
	return 0;
    }
    
    return cli_set(h, vars, arg);
}
