/*
 *  CVS Version: $Id: quagga.c,v 1.18 2013/08/09 13:27:46 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <getopt.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_cli.h>

/* rost lib */
#include <quaggapi.h>

/*
 * Plugin start
 * Just set the QUAGGA_DIR option if given on command line.
 */
int
plugin_start(clicon_handle h, int argc, char **argv)
{
    char c;

    optind = 0;
    opterr = 0;
    while ((c = getopt(argc, argv, "q:")) != -1) {
	switch (c) {
	case 'q' : /* debug */
	    if (optarg && strlen(optarg))
		clicon_option_str_set(h, "QUAGGA_DIR", optarg);
	    break;
	}
    }

    return 0;
}

/*
 * interface callback for cli_set parser
 */
int
quagga_acl_cb(cvec *vars, cg_var *cv, cg_var *arg)
{
    char *name;
    extern struct qa_mode cli_mode;

    if ((name = cv_name_get(cv)) == NULL)
	return -1;

    if (*name == '!')
	name++;

    if (!strcmp (name, "name")) {
	cv_type_set(cv, CGV_STRING);
	cv_string_set(cv, cli_mode.u.aclname);
	return 0;
    }

    if (!strcmp (name, "id")) {
	cv_type_set(cv, CGV_UINT32);
	cv_int_set(cv, cli_mode.u.aclid);
	return 0;
    }

    return -1;    
}

