/*
 *  CVS Version: $Id: system.c,v 1.20 2013/01/25 10:05:46 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_OSR_CONFIG_H
#include "osr_config.h" /* generated by config & autoconf */
#endif /* HAVE_OSR_CONFIG_H */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <errno.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_cli.h>

/* local */
#include "ios.h"

int 
system_interface(void *handle, cvec *vars, cg_var *arg)
{
    cg_var *ifname;

    if ((ifname = cvec_find_var(vars, "name")) == NULL) {
	cli_output(stderr, "Could not find 'name' in variable vector\n");
	return 0;
    }

    if (if_nametoindex(cv_string_get(ifname)) == 0) {
	cli_output(stderr, "System interface '%s' does not exist\n", cv_string_get(ifname));
	return 0;
    }

    return cli_ios_mode(handle, vars, arg);
}
