/*
 *  CVS Version: $Id: dhcp-client.c,v 1.6 2013/08/05 14:30:44 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_OSR_CONFIG_H
#include "osr_config.h" /* generated by config & autoconf */
#endif /* HAVE_OSR_CONFIG_H */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <netinet/in.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_backend.h>

/* lib */
#include "system.h"
#include "interface.h"

#define DHCPCD			"dhcpcd"
#define DHCPCD_CONF		"/etc/dhcpcd.conf"
#define DHCPCD_START_CMD	DHCPCD " -b -q %s"
#define DHCPCD_STOP_CMD		DHCPCD " -x -b -q %s"

#if 0
/* Flag set if config changed and we need to rebind dhcpcd */
static int dhcpcd_rebind;
#endif

#if 0
#define DHCPCD_BASE	\
    "quiet\n"		\
    "hostname\n"	\
    "clientid\n"	\
    "nohook lookup-hostname\n"	\
    "nohook resolv.conf\n"	\
    "noipv4ll\n"
#endif

#if 0
/* lvmap formats for db to config-file transforms */
static struct lvmap dhcpcd_conf_fmts[] = {
    {"dhcp.client.interface[]", "interface $name", NULL, LVPRINT_CMD},
//    {"dhcp.client.", "logconfig\t" NTP_LOGGING "\n", NULL, LVPRINT_CMD},
  {NULL, NULL, NULL}
};
#endif

/*
 * Commit callback. 
 * We do nothing here but simply create the config based on the current 
 * db once everything is done as if will then contain the new config.
 */
int
dhcpcd_commit(clicon_handle h, char *db,
	      trans_cb_type tt, 
	      lv_op_t op,
	      char *key,
	      void *arg)
{
    int retval = -1;
    char *cmd = NULL;
    cg_var *cgv = NULL;

    /* Get interface name */
    cgv = dbvar2cv (db, key, "name");
    if (cgv == NULL) {
	clicon_err(OE_DB, errno , "Failed get interface name from database");
	goto catch;
    }

    if (op == LV_SET)
	cmd = chunk_sprintf (__FUNCTION__, DHCPCD_START_CMD, cv_string_get(cgv));
    else
	cmd = chunk_sprintf (__FUNCTION__, DHCPCD_STOP_CMD, cv_string_get(cgv));
    if (cmd == NULL) {
	clicon_err(OE_UNIX, errno , "chunk");
	goto catch;
    }
    
    clicon_proc_run (cmd, NULL, 0);
    retval = 0;

catch:
    if (cgv) 
	cv_free(cgv);
    unchunk_group(__FUNCTION__);
    return retval;
}


/*
 * plugin initialization
 */
int
plugin_init(clicon_handle h)
{
    int retval = -1;
    char *key = "interface[].unit[].inet.dhcp_client";

    if (dbdep(h, TRANS_CB_COMMIT, dhcpcd_commit, (void *)NULL, 1, key)==NULL) {
	clicon_debug(1, "failed to create dependency '%s'", key);
	goto done;
    }
    clicon_debug(1, "created dependency '%s'", key);
    retval = 0;

  done:
    return retval;
}

/*
 * plugin start
 */
int
plugin_start(clicon_handle h, int argc, char **argv)
{
    return 0;
}

/*
 * reset reload-flag before we start.
 */
int
transaction_begin(clicon_handle h)
{
#if 0
    dhcpcd_rebind = 0;
#endif
    return 0;
}

/*
 * if commit is successful the current db has been replaced by the committed 
 * candidate. we simply re-create a new dhcpcd.conf based on it.
 */
int
transaction_end(clicon_handle h)
{
#if 0
    int i;
    int retval = -1;
    FILE *out = NULL;
    int   npairs;
    struct db_pair *pairs;
    int allow_printed = 0;
    int deny_printed = 0;
    cg_var *cv = NULL;
    int len;
    struct clicon_if *iflist;
    
    if (dhcpcd_rebind == 0)
	return 0; /* nothing has changed */
    
    /* Get all interfaces for deny list */
    if (clicon_iflist_get(NULL, __FUNCTION__, &iflist, &len) < 0)
	return -1;

    npairs = db_regexp(candidate, "dhcp\\.client\\.interface\\.[0-9]+",
		       __FUNCTION__, &pairs, 0);
    if (npairs < 0) {
	clicon_err(OE_UNIX, errno, "%s: db_regexp", __FUNCTION__);
	goto catch;
    }
    
    /* Open new temp config file */
    if ((out = fopen(DHCPCD_CONF_NEW, "w")) == NULL) {
	clicon_err(OE_CFG, errno, "%s: fopen: %s", __FUNCTION__, strerror(errno));
	goto catch;
    }

    /* loop through list */
    for (i = 0; i < npairs; i++) {
	cv = dbvar2cv(candidate, pairs[i].dp_key, "name");
	if (cv == NULL) {
	    clicon_err(OE_UNIX, errno, "%s: dbvar2cv", __FUNCTION__);
	    goto catch;
	}

	if (allow_printed == 0) {
	    fprintf(out, "allowinterfaces");
	    allow_printed++;
	}
	fprintf (out, " %s", cv_string_get(cv));

	/* Remove from deny list */
	for (i = 0; i < len; i++) {
	    if (strcmp(iflist[i].ci_name, cv_string_get(cv)) == 0) {
		iflist[i].ci_name[0] = '\0';
		break;
	    }
	}
	cv_free(cv);
	cv = NULL;
    }
    if (allow_printed > 0)
	fprintf (out, "\n");
    
    for (i = 0; i < len; i++) {
	if (strlen(iflist[i].ci_name) == 0)
	    continue;
	if (deny_printed == 0) {
	    fprintf(out, "denyinterfaces");
	    deny_printed++;
	}
	fprintf(out, " %s", iflist[i].ci_name);
    }
    if (deny_printed > 0)
	fprintf (out, "\n");
    
    fprintf (out, DHCPCD_BASE);
    fclose(out);
    out = NULL;

    if (rename(DHCPCD_CONF_NEW, DHCPCD_CONF) < 0) {
	clicon_err(OE_UNIX, errno, "%s: rename", __FUNCTION__);
	goto catch;
    }

    /* Rebind dhcpcd */
    if (debug)
	fprintf(stderr, "Re-bindind dhcpcd\n");
    clicon_proc_run (DHCPCD, NULL, 0);
    retval = 0;
    
catch:
    if (out)
	fclose(out);
    if (cv)
	cv_free(vh);
    unchunk_group(__FUNCTION__);
    return retval;
#else
    return 0;
#endif
}
