/*
 *  CVS Version: $Id: linux-tunnel.c,v 1.7 2013/08/05 14:30:44 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <net/if.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <regex.h>
#include <ctype.h>


#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_backend.h>

/* rost lib */
#include <quaggapi.h>

/* local */
#include "linux-tunnel.h"

static int tunnel_new(clicon_handle, char *, lv_op_t, char *key, void *arg);
static int tunnel_action(clicon_handle, char *, lv_op_t, char *key, void *arg);

#define ROST_CURKEY	"ROST_CURKEY"

struct tunnel_action {
    char *key;
    trans_cb cb;
    char *set; 
    char *del;
};
static struct tunnel_action tactions[] = {
    {
	"interface[].unit[]",
	tunnel_new,
	NULL,
	NULL,
    },

    {
	"interface[].unit[].tunnel.source",
	tunnel_action,
	"ip tunnel change $" ROST_CURKEY "->name local $" ROST_CURKEY "->source",
	"ip tunnel change $" ROST_CURKEY "->name local $" ROST_CURKEY "->source",
    },

    {
	"interface[].unit[].tunnel.destination",
	tunnel_action,
	"ip tunnel change $" ROST_CURKEY "->name remote $" ROST_CURKEY "->destination",
	"ip tunnel change $" ROST_CURKEY "->name remote $" ROST_CURKEY "->destination",
    },

    {
	"interface[].unit[].tunnel.csum",
	tunnel_action,
	"ip tunnel change $" ROST_CURKEY "->name csum",
	"ip tunnel change $" ROST_CURKEY "->name csum",
    },

    {
	"interface[].unit[].tunnel.nopmtu",
	tunnel_action,
	"ip tunnel change $" ROST_CURKEY "->name nopmtudisc",
	"ip tunnel change $" ROST_CURKEY "->name pmtudisc",
    },

    {
	"interface[].unit[].tunnel.tos",
	tunnel_action,
	"ip tunnel change $" ROST_CURKEY "->name tos $" ROST_CURKEY "->tos",
	"ip tunnel change $" ROST_CURKEY "->name tos 0",
    },

    {
	"interface[].unit[].tunnel.ttl",
	tunnel_action,
	"ip tunnel change $" ROST_CURKEY "->name ttl $" ROST_CURKEY "->ttl",
	"ip tunnel change $" ROST_CURKEY "->name ttl 0",
    },

    {
	"interface[].unit[].tunnel.key",
	tunnel_action,
	"ip tunnel change $" ROST_CURKEY "->name key $" ROST_CURKEY "->key",
	"ip tunnel change $" ROST_CURKEY "->name key 0",
    },
    

    {NULL, NULL, NULL },
};

/*
 * Commit callback. 
 */
static int
tunnel_new(clicon_handle h,
	   char *db,
	   lv_op_t op,
	   char *key,
	   void *arg)
{
    int retval = -1;
    cg_var *cgv = NULL;
    char matchlen;
    char *ifname = NULL;
    char *mode = NULL;
    char *cmd, *cmd2;
    struct in_addr lo;
    char *modekey;
    char *num;
    
    /* Get interface name */
    cgv = dbvar2cv (db, key, "name");
    if (cgv == NULL) {
	clicon_err(OE_DB, errno , "Failed get interface name from database");
	goto catch;
    }
    if ((ifname = strdup(cv_string_get(cgv))) == NULL) {
	clicon_err(OE_UNIX, errno , "strdup");
	goto catch;
    }
    cv_free(cgv);
    
    /* Is this a tunnel interface? */
    if ((matchlen = clicon_strmatch(ifname, LINUX_TUNNEL_IFRX_FULL, NULL)) < 0)
	goto catch;
    if (matchlen == 0) {    /* Not a tunnel interface, ignore */
	retval = 0;
	clicon_debug(1, "Linux Tunnel: Ignoring interface %s", ifname);
	goto catch;
    }
    
    /* Get interface name */
    modekey = chunk_sprintf(__FUNCTION__, "%s.tunnel.mode", key);
    if (modekey == NULL) {
	clicon_err(OE_UNIX, errno , "chunk");
	goto catch;
    }
    cgv = dbvar2cv (db, modekey, "mode");
    if (cgv == NULL) {
	clicon_err(OE_DB, errno , "Failed get tunnel mode from database");
	goto catch;
    }
    if ((mode = strdup(cv_string_get(cgv))) == NULL) {
	clicon_err(OE_UNIX, errno , "strdup");
	goto catch;
    }
    cv_free(cgv);
    

    if (op == LV_SET) {
	lo.s_addr = INADDR_LOOPBACK;
	num = &ifname[strlen(ifname)-1];
	while(isdigit(*(num-1)))
	    num--;
	lo.s_addr = htonl(INADDR_LOOPBACK + atoi(num));
	cmd = chunk_sprintf(__FUNCTION__,
			    "ip tunnel add %s mode %s local %s remote %s",
			    ifname,
			    mode, 
			    inet_ntoa(lo),
			    inet_ntoa(lo));
	cmd2 = chunk_sprintf(__FUNCTION__, "ip link set dev %s up", ifname);
    } else {
	cmd = chunk_sprintf(__FUNCTION__, "ip link set dev %s down", ifname);
	cmd2 = chunk_sprintf(__FUNCTION__, "ip tunnel del %s", ifname);
    }
    if (cmd == NULL || cmd2 == NULL) {
	clicon_err(OE_DB, errno, "chunk_sprintf");
	goto catch;
    }
    
    clicon_debug(1, "Run: \"%s\"", cmd);
    clicon_proc_run(cmd, NULL, 0);
    clicon_debug(1, "Run: \"%s\"", cmd2);
    clicon_proc_run(cmd2, NULL, 0);
    
    retval = 0;
    
catch:
    if (ifname)
	free(ifname);
    if (mode)
	free(mode);
    unchunk_group(__FUNCTION__);
    
    return retval;
}

/*
 * Commit callback. 
 */
static int
tunnel_action(clicon_handle h,
	      char *db,
	      lv_op_t op,
	      char *key,
	      void *arg)
{
    char *fmt;
    char *cmd = NULL;
    struct tunnel_action *t;
    
    t = (struct tunnel_action *)arg;
    fmt = (op == LV_SET) ? t->set : t->del;

    /* Get variable list from database */
    if (clicon_option_str_set(h, ROST_CURKEY, key))
	return -1;
    cmd = clicon_db2txt_buf(h, db, fmt);
    clicon_option_del(h, ROST_CURKEY);
    if (cmd == NULL) {
	clicon_err(OE_PLUGIN, 0, "Failed to format tunnel command");
	return -1;
    }
    clicon_debug(1, "Run: \"%s\"", cmd);
    clicon_proc_run(cmd, NULL, 0);

    return 0;
}



/*
 * Plugin initialization
 */
int
plugin_init(clicon_handle h)
{
    int i;
    char *key;
    int retval = -1;
    
    for (i = 0; tactions[i].key != NULL; i++) {
	key = tactions[i].key;
	if (dbdep(h, 0, tactions[i].cb, &tactions[i], key) == NULL) {
	    clicon_debug(1, "Failed to create dependency '%s'", key);
	    goto done;
	}
	clicon_debug(1, "Created dependency '%s'", key);
    }

    retval = 0;
  done:
    return retval;
}
