/*
 *  CVS Version: $Id: linux-vlan.c,v 1.9 2013/08/05 14:30:44 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <net/if.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <regex.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_backend.h>

/* rost lib */
#include "quaggapi.h"
#include <linux-vlan.h>

/* local */

/*
 * Commit callback. 
 */
static int
vlan_commit(clicon_handle h,
	    char *db,
	    trans_cb_type tt, 
	    lv_op_t op,
	    char *key,
	    void *arg)
{
    int retval = -1;
    cg_var *cgv = NULL;
    char matchlen;
    char *ifname;
    char *dot;
    char *cmd, *cmd2;

    /* Get interface name */
    cgv = dbvar2cv (db, key, "name");
    if (cgv == NULL) {
	clicon_err(OE_DB, errno , "Failed get interface name from database");
	goto catch;
    }
    ifname = cv_string_get(cgv);

    if ((matchlen = clicon_strmatch(ifname, LINUX_VLAN_IFRX_FULL, NULL)) < 0)
	goto catch;
    if (matchlen == 0) {    /* Not a vlan interface, ignore */
	retval = 0;
	clicon_debug(1, "Linux VLAN: Ignoring interface %s", ifname);
	goto catch;
    }
    
    dot = strrchr(ifname, '.');
    *dot = '\0';

    if (if_nametoindex(ifname) == 0) {
	clicon_err(OE_CFG, ENODEV, "Parent interface '%s'", ifname);
	goto catch;
    }

    /* range check vlan id */
    if (atoi(dot+1) > MAX_VID || atoi(dot+1) < MIN_VID) {
	clicon_err(OE_CFG, ERANGE, "VLAN ID: %s", dot+1);
	goto catch;
    }

    if (op == LV_SET) {
	cmd = chunk_sprintf(__FUNCTION__,
			    "ip link add link %s name %s.%s type vlan id %s",
			    ifname, ifname, dot+1, dot+1);
	cmd2 = chunk_sprintf(__FUNCTION__,
			     "ip link set dev %s.%s up", ifname, dot+1);
    } else {
	cmd = chunk_sprintf(__FUNCTION__,
			     "ip link set dev %s.%s down", ifname, dot+1);
	cmd2 = chunk_sprintf(__FUNCTION__,
			    "ip link delete dev %s.%s",
			    ifname, dot+1);
    }
    if (cmd == NULL || cmd2 == NULL) {
	clicon_err(OE_DB, errno, "chunk_sprintf");
	goto catch;
    }
    
    clicon_debug(1, "Run: \"%s\"", cmd);
    clicon_proc_run(cmd, NULL, 0);
    clicon_debug(1, "Run: \"%s\"", cmd2);
    clicon_proc_run(cmd2, NULL, 0);
    
    retval = 0;
    
catch:
    if (cgv) 
	cv_free(cgv);
    unchunk_group(__FUNCTION__);
    
    return retval;
}


/*
 * Plugin initialization
 */
int
plugin_init(clicon_handle h)
{
    char *key;
    int retval = -1;

    key = "interface[].unit[]";
    if (dbdep(h, TRANS_CB_COMMIT, vlan_commit, (void *)NULL, 1, key) == NULL) {
	clicon_debug(1, "Failed to create dependency '%s'", key);
	goto done;
    }
    clicon_debug(1, "Created dependency '%s'", key);

    retval = 0;
  done:
    return retval;
}
