/*
 *  CVS Version: $Id: system.c,v 1.23 2014/01/09 04:32:16 benny Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <syslog.h>
#include <netinet/in.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_backend.h>

/* Callback declarations */
static int system_hostname_commit(clicon_handle h, lv_op_t, commit_data);

/* Map of key-callback pairs for system */
struct {
    char *key;
    trans_cb cb;
} system_depmap[] = {
    {"system.hostname", system_hostname_commit},

    {NULL, NULL},
};


/*
 * Plugin initialization
 */
int
plugin_init(clicon_handle h)
{
    int i;
    char *key;
    int retval = -1;

    for (i = 0; system_depmap[i].key != NULL; i++) {
	key = system_depmap[i].key;
	if (dbdep(h, 0, system_depmap[i].cb, (void *)NULL, key) == NULL){
	    clicon_debug(1, "Failed to create dependency '%s'", key);
	    goto done;
	}
	clicon_debug(1, "Created dependency '%s'", key);
    }	
    retval = 0;
  done:
    return retval;
}

/*
 * Plugin start
 */
int
plugin_start(clicon_handle h, int argc, char **argv)
{
    return 0;
}

/*
 * Reset system state
 */
int
plugin_reset(clicon_handle h, char *db)
{
    char hostname[HOST_NAME_MAX];
    char *fmt;
    int retval = -1;

    if (gethostname(hostname, HOST_NAME_MAX) < 0)
	snprintf(hostname, HOST_NAME_MAX-1, "rost");
    fmt = chunk_sprintf(__FUNCTION__, 
			"system.hostname $hostname=\"%s\"", 
			hostname);
    /* (1) Default hostname*/
    if (db_lv_op(clicon_dbspec_key(h), db, LV_SET, fmt, NULL) < 0)
	goto done;
    retval = 0;
  done:
    unchunk_group(__FUNCTION__);
    return retval;
}


/*
 * Hostname commit callback. 
 */
static int
system_hostname_commit(clicon_handle h, lv_op_t op, commit_data d)
{
    int ret;
    cg_var *cgv;
    char *hostname;
    
    /* Get configured hostname from db */
    if (op == LV_SET)
        cgv = clicon_dbgetvar(commit_db2(d), "system.hostname", "hostname");
    else
	cgv = NULL;

    if (cgv == NULL || !strlen(cv_string_get(cgv)))
	hostname = "Router";
    else
	hostname = cv_string_get(cgv);

    if ((ret = sethostname(hostname, strlen(hostname))) != 0) 
	clicon_err(OE_UNIX, errno, "%s: sethostname", __FUNCTION__);
    
    return ret;
}

