/*
 *  CVS Version: $Id: interface.c,v 1.10 2012/01/03 10:35:33 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_OSR_CONFIG_H
#include "osr_config.h" /* generated by config & autoconf */
#endif /* HAVE_OSR_CONFIG_H */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <inttypes.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <netinet/in.h>

/* cligen */
#include <cligen/cligen.h>

/* clicon */
#include <clicon/clicon.h>

#include "interface.h"

/*
 * clicon_iflist_get
 * Go through all interfaces on the system and allocate an array
 * Uses getifaddrs() which is really made for getting addresses so it
 * is not an optimal method. You have to do some sorting to pick unique
 * interfaces. But at least it is seems portable.
 *
 * prefix is the first part of the interface name for matching
 * Note that on success, iflist0 must be deallocated with unchunk().
 */
int 
clicon_iflist_get(char *prefix, const char *label, 
	       struct clicon_if **iflist0, int *len)
{
    int              ifnr = 0;
    int              retval = -1;
    struct ifaddrs  *ifaddr, *ifa, *ifa1;
    struct clicon_if    *iflist = NULL; 

    /* First count interfaces. */
    if (getifaddrs(&ifaddr) == -1) {
	clicon_err(OE_UNIX, errno, "%s: getifaddrs", __FUNCTION__);
	return -1;
    }
    for (ifa = ifaddr, ifnr=0; ifa != NULL; ifa = ifa->ifa_next) {
	/* Check if already in list */
	for (ifa1 = ifaddr; ifa1 != ifa; ifa1 = ifa1->ifa_next)
	    if (strcmp (ifa1->ifa_name, ifa->ifa_name) == 0)
		break;
	if (ifa1 != ifa)
	    continue;  /* Already in list */
	if ((iflist = rechunk(iflist, (ifnr+1)*sizeof(struct clicon_if), label)) == NULL){
	    clicon_err(OE_UNIX, errno, "%s: rechunk", __FUNCTION__);
	    goto err;
	}
	if (prefix)
	    if (strncmp(prefix, ifa->ifa_name, strlen(prefix)) != 0)
		continue;
	strncpy(iflist[ifnr].ci_name, ifa->ifa_name, IFNAMSIZ);
	iflist[ifnr].ci_flags = ifa->ifa_flags;
	ifnr++;
    }
    *iflist0 = iflist;
    *len = ifnr;
    retval = 0;
  err: 
    freeifaddrs(ifaddr);
    unchunk_group(__FUNCTION__);
    return retval;
}


