/*
 *  CVS Version: $Id: syslog.c,v 1.10 2011/11/19 12:34:29 benny Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_OSR_CONFIG_H
#include "osr_config.h" /* generated by config & autoconf */
#endif /* HAVE_OSR_CONFIG_H */

#include <stdio.h>
#include <netinet/in.h>
#include <sqlite3.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>

/* lib */
#include "osr_syslog.h" 

/*
 * Execute SQL query. (lib)
 * Arguments:
 *   flags	- flags to sqlite3_open_v2()
 *   query	- A semi-colon separated list of SQL queries.
 *   cb		- An optional callback. See sqlite3_exec()
 *   cbarg	- Optional argument passed to callback
 * returns 0 on success -1 on error
 */
int
syslog_sqlite3_exec(char *filename,
		    int flags,
		    char *query,
		    int (*cb)(void *, int, char **, char **),
		    void *cbarg)
{
    int ret;
    sqlite3 *dbh;
    char *err;


    ret = sqlite3_open_v2(filename, &dbh, flags, NULL);
    if (ret != SQLITE_OK) {
	clicon_err(OE_SYSLOG, ret, "%s", sqlite3_errmsg(dbh));
	return -1;
    }

    sqlite3_busy_timeout(dbh, 1000);
    ret = sqlite3_exec(dbh, query, cb, cbarg, &err);
    if (ret != SQLITE_OK){
	clicon_err(OE_SYSLOG, ret, "%s", sqlite3_errmsg(dbh));
	ret = -1;
    }
    sqlite3_close(dbh);

    return ret;
}


