/*
 *  CVS Version: $Id: system.c,v 1.14 2013/07/01 10:40:54 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/vfs.h>
#include <sys/types.h>
#include <sys/param.h>
#include <dirent.h>
#include <unistd.h>
#include <ctype.h>
#include <net/if.h>
#include <netinet/in.h>
#include <pwd.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_cli.h>

/* lib */
#include "system.h"

/* Have we read product file? */
static int is_initialized = 0;

/*
 * Read procut number and serialnr from product file, and set environment vars:
 * typically RNR_PRODUCT and RNR_SERIALNR
 * Then call the rost_get_ functions above
 */
int
rost_product2env()
{
    FILE *f;
    char line[1024];
    char *name, *val;

    if (is_initialized)
	return 0;

    if ((f = fopen (ROST_PRODUCT_FILE, "r")) == NULL){
#if 0 /* ignored */
        clicon_err(OE_UNIX, errno, "Failed to open %s", ROST_PRODUCT_FILE);
        return -1;
#else
	return 0;
#endif
    }
    while (fgets(line, sizeof(line), f) != NULL){
	line[strlen(line)-1] = '\0';
	val = line;
	name = strsep(&val, "=");
	if (setenv(name, val, 1) < 0){
	    clicon_err(OE_UNIX, errno, "setenv");
	    return -1;
	}
    }
    fclose(f);
    is_initialized = 1;

    return 0;
}


/*
 * XXX: avoid /proc
 */
int
rost_uptime(int *sec)
{
    FILE *f;
    double u; /* seconds */

    /* Open /proc filesystem */
    if ((f = fopen ("/proc/uptime", "r")) == NULL){
        clicon_err(OE_UNIX, errno, "Failed to open /proc/uptime");
        return -1;
    }
    if (fscanf(f, "%lf", &u) != 1){
	clicon_err(OE_UNIX, errno, "Error when reading /proc/uptime");
        fclose(f);
        return -1;
    }
    fclose(f);
    *sec = (int)u;
    return 0;
}

int
rost_get_serialno(char *serialnr, int len)
{
    char *val;

    rost_product2env() ;

    if ((val = getenv("RNR_SERIALNR")) != NULL)
	strncpy(serialnr, val, len);
    else
	strncpy(serialnr, "unknown", len);
    return 0;
}

int
rost_get_product(char *product, int len)
{
    char *val;

    rost_product2env();
    
    if ((val = getenv("RNR_PRODUCT")) != NULL)
	strncpy(product, val, len);
    else
	strncpy(product, "unknown", len);
    return 0;
}


/*
 * The below is difficult to port and therefore moved from clicon
 */

#ifdef linux
/*
 * Send 'sig' (if not 0) to all processes matching 'name'.
 * Return the number of matches.
 */
int
rost_proc_killbyname (const char *name, int sig)
{
  /* XXXX FIXME. Should scan /proc/<pid>/status */
  char buf[512];
  snprintf (buf, sizeof (buf)-1, "pkill -%d %s", sig, name);

  return clicon_proc_run (buf, NULL, 0);
}
#endif /* Linux */


#ifdef BSD
/*
 * Send 'sig' (if not 0) to all processes matching 'name'.
 * Return the number of matches.
 */
int
rost_proc_killbyname (const char *name, int sig)
{
	int
		i,
		nproc,
		nmatch,
		mib[3];
	size_t
		size;
	struct proc
		*p;
	struct kinfo_proc
		*kp = NULL;

	mib[0] = CTL_KERN;
	mib[1] = KERN_NPROCS; /* KERN_MACPROC, KERN_PROC */
	size = sizeof (nproc);
	if (sysctl(mib, 2, &nproc, &size, NULL, 0) < 0)
		return -1;

	size = nproc * sizeof(struct kinfo_proc);
	kp = chunk(size * sizeof(char), "bsdkill");
	if (kp == NULL)
		goto error;

	mib[1] = KERN_PROC;
	mib[2] = KERN_PROC_ALL;
	
	if (sysctl(mib, 3, kp, &size, NULL, 0) < 0)
		goto error;
	
	nproc = size / sizeof(struct kinfo_proc);
	for (nmatch = i = 0; i < nproc; i++) {
		p = (struct proc *)&kp[i].kp_proc;
		if (!strcmp (name, p->p_comm)) {
			nmatch++;
			kill (p->p_pid, sig);
		}
	}

	unchunk (kp);
	return nmatch;

 error:
	if (kp)
		unchunk (kp);
	return -1;
}
#endif /* BSD */

struct errvec{
    char *ev_str;
    int   ev_err;
};

/* Hardcoded to QUAGGA, move to app-layer */
static struct errvec QV[] = {
    {"QUAGGA_SUCCESS",              0},
    {"QUAGGA_WARNING",              1},
    {"QUAGGA_ERR_NO_MATCH",         2},
    {"QUAGGA_ERR_AMBIGUOUS",        3},
    {"QUAGGA_ERR_INCOMPLETE",       4},
    {"QUAGGA_ERR_EXEED_ARGC_MAX",   5},
    {"QUAGGA_ERR_NOTHING_TODO",     6},
    {"QUAGGA_COMPLETE_FULL_MATCH",  7},
    {"QUAGGA_COMPLETE_MATCH",       8},
    {"QUAGGA_COMPLETE_LIST_MATCH",  9},
    {"QUAGGA_SUCCESS_DAEMON",      10},
    {"QUAGGA_NO_CONTACT",          11},
    {NULL,            -1}
};


/*!
 * \brief Special error message for quagga routing, using clicon_err as backend
 *
 * This is a kludge to replace clicon_err(OE_ROUTING..) calls with 
 * application-specific code inside clicon. We have now moved it outside 
 * of clicon and placed it here instead.
 */
int
rost_err(int suberr, char *reason, ...)
{
    va_list        args;
    struct errvec *ev;
    char          *errstr;
    int            len;
    char          *msg = NULL;
    int            retval = -1;

    for (ev=QV; ev->ev_err != -1; ev++)
	if (ev->ev_err == suberr)
	    break;
    errstr = ev?(ev->ev_str?ev->ev_str:"unknown"):"ROST unknown error";

    /* first round: compute length of error message */
    va_start(args, reason);
    len = vsnprintf(NULL, 0, reason, args);
    va_end(args);
    
    /* second round: compute write message from reason and args */
    va_start(args, reason);
    if (vsnprintf(msg, len+1, reason, args) < 0){
	va_end(args);
	fprintf(stderr, "vsnprintf: %s\n", strerror(errno)); /* dont use clicon_err here due to recursion */
	goto done;
    }
    va_end(args);
    retval = clicon_err(OE_ROUTING, 0, "%s: %s", 
		      msg,
		      errstr);
  done:
    if (msg)
	free(msg);
    return retval;
}
