/*
 *  CVS Version: $Id: cli_expand.c,v 1.4 2014/01/23 21:14:36 benny Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 * * 
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <signal.h>
#include <errno.h>
#include <unistd.h>
#include <dirent.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <ifaddrs.h>
#include <pwd.h>
#include <sys/param.h>
#include <sys/mount.h>
#include <sys/stat.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_cli.h>

/* lib */

#include "cli_expand.h"

/*
 * expand callbacks. These functions occur in the cligen specification
 * files in eg <string expand:expand_bgp_as()>
 */
int
expand_bgp_as(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_db_variable(h, clicon_candidate_db(h), "router.bgp", "as", nr, commands);
}

int
expand_bgp_neighbor(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_db_variable(h, clicon_candidate_db(h), "router.bgp.neighbor[]", "neighbor", nr, commands);
}

int
expand_interface(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_db_variable(h, clicon_candidate_db(h), "interface[]", "name", nr, commands);
}

int
expand_user(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_db_variable(h, clicon_candidate_db(h), "system.login.user[]", "user", nr, commands);
}

int
expand_configfile(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_dir(ROST_CONFIG_DIR, nr, commands, S_IFREG, 0);
}

int
expand_snapshot(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    char           *dir;

    dir = clicon_archive_dir(h);
    return expand_dir(dir, nr, commands, S_IFREG, 1);
}

int
expand_flash(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_dir(ROST_IMAGE_DIR, nr, commands, S_IFREG, 1);
}

int
expand_home(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_dir(getenv("HOME"), nr, commands, S_IFREG, 1);
}

int
expand_cwd(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_dir(getcwd(NULL, PATH_MAX), nr, commands, S_IFREG, 1);
}

int
expand_acl(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_db_symbol(h, "access-list", 1, nr, commands);
}

int
expand_prefixlist(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_db_symbol(h, "ipv4.prefix-list", 2, nr, commands);
}

int
expand_routemap(clicon_handle h, char *name, cvec *vars, cg_var *arg, int *nr, char ***commands, char ***helptexts)
{
    return expand_db_variable(h, clicon_candidate_db(h), "route-map[]", "name", nr, commands);
}


