/*
 *  CVS Version: $Id: cli_auth.c,v 1.5 2013/08/05 14:30:56 olof Exp $
 *
 *  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of ROST.
 *
 *  ROST is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ROST is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along wth ROST; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 *
 */
#ifdef HAVE_ROST_CONFIG_H
#include "rost_config.h" /* generated by config & autoconf */
#endif /* HAVE_ROST_CONFIG_H */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define _XOPEN_SOURCE       /* See feature_test_macros(7) */
#include <unistd.h>
#include <errno.h>
#include <sys/types.h>
#include <pwd.h>
#ifdef HAVE_CRYPT_H
#include <crypt.h>
#endif 


/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_cli.h>

#include "cli_auth.h"

/*
 * cli_passwd_cleartext
 * Get password in cleartext.
 */ 
int
cli_passwd_cleartext(clicon_handle h, cvec *vars, cg_var *arg)
{
    char           passwd[128];
    char           confirm[128];
    char          *encrypted_password;
    //  char          *user;
    char          *ptr;
    int            retval;
    cvec          *new;
    cg_var        *cv;

//    user = vars.vr_vec[1].var_string;
    memset(passwd, 0, sizeof(passwd));
    printf("New password: ");
    cligen_echo_off();

    if (fgets (passwd, sizeof (passwd) - 1, stdin) == NULL){
	cligen_echo_on();
	printf("\n");
	return -1;
    }
    if ((ptr = strchr(passwd, '\n')) != NULL)
      *ptr = '\0';

    cligen_echo_on();
    printf("\n");

    memset(confirm, 0, sizeof(confirm));
    printf("Retype new password: ");
    cligen_echo_off();
    if (fgets (confirm, sizeof (confirm) - 1, stdin) == NULL){
	cligen_echo_on();
	printf("\n");
	return -1;
    }
    if ((ptr = strchr(confirm, '\n')) != NULL)
      *ptr = '\0';
    cligen_echo_on();
    printf("\n");

    if (strlen(passwd) != strlen(confirm) || strcmp(passwd, confirm)) {
	printf ("Mismatch!\n");
	return -1;
    }
    
    if (strlen(passwd) <= 0) {
	printf ("Password too short!\n");
	return -1;
    }

    if (strcmp(passwd, confirm) != 0) {
	printf ("Mismatch!\n");
	return -1;
    }
#if 1
    encrypted_password = crypt(passwd, "$1$xx$");
#else
    encrypted_password = NULL;
#endif

    memset(passwd, 0, sizeof(passwd));
    memset(confirm, 0, sizeof(confirm));

    /* Create copy of argc, argv and add encrypted passwd last */
    if ((new = cvec_dup(vars)) == NULL){
	fprintf(stderr, "%s: cvec_new: %s\n", __FUNCTION__, strerror(errno));
	return -1;
    }
    cv = cvec_add(new, CGV_STRING);
    cv_string_set(cv, encrypted_password);
    retval = cli_set(h, new, arg);
    cvec_free(new);
    return retval;
}

/*
 * cli_change_user
 * Get password in cleartext.
 */ 
int
cli_change_user(clicon_handle h, cvec *vars, cg_var *arg)
{
#ifdef notyet
    char          *user;
    int            repeat = 3;
    char           passwd[128];
    struct termios term_set;
    int          attempts;
    char        *pw_passwd = NULL;
    struct spwd *spw;
    cg_var *cv1 = cvec_i(vars, 1);

    user = cv_string_get(cv1);
    memset(passwd, 0, sizeof(passwd));
    spw = getspnam(user);
    if (spw == NULL){
	if (errno)
	    fprintf(stderr, "%s: getspnam\n", __FUNCTION__);
	else
	    fprintf(stderr, "user %s not found in shadow password file\n", user);
	return 0;
    }
    else
	pw_passwd = spw->sp_pwdp;
    for (attempts = 3; attempts; attempts--) {
	/*  The  calling  process  should  zero the password as soon as possible */
	printf("Password: ");
	cligen_echo_off();
	if (fgets (passwd, sizeof (passwd) - 1, stdin) == NULL){
	    echo_on(&term_set);
	    printf("\n");
	    return -1;
	}
        if (cli_getln (buf, sizeof (buf)) != 0){
	    echo_on();
	    printf("\n");
	    break;
	}
	echo_on();
	printf("\n");
	/*
	 * get user info again:  may have changed 
	 */
	spw = getspnam(user);
	if (spw == NULL){
	    if (errno)
		perror("ptcli-auth: getspnam");
	    else
		fprintf(stderr, "user %s not found in shadow password file\n", user);
	    return 0;
	}
	if (strlen(buf)==0 || !cli_auth_login(buf, pw_passwd)) {
	    fprintf(stdout, "Invalid password\n");
	    memset(buf, 0, sizeof(buf));
	    if (repeat)
		sleep (1);
	    else
		break;
	}
	else{
	    memset(buf, 0, sizeof(buf));
	    /* Here actually change the user,... */
	}
    }
#endif
    return 0; /* failure */
}

